// lib/utils/ingredient_substitutes.dart

const Map<String, String> ingredientSubstitutes = {
  "black truffles": "porcini mushrooms",
  "white truffles": "mushroom medley",
  "foie gras": "chicken liver",
  "saffron": "turmeric",
  "gold leaf": "edible glitter",
  "yuzu": "lemon juice",
  "wasabi": "horseradish",
  "kumquat": "orange segments",
  "caviar": "roe-free fish eggs",
  "bottarga": "grated hard cheese (like Parmesan)",
  "matsutake mushrooms": "shiitake mushrooms",
  "morel mushrooms": "cremini mushrooms",
  "chanterelle mushrooms": "button mushrooms",
  "lobster": "shrimp or crayfish",
  "langoustine": "shrimp",
  "king crab": "snow crab",
  "wild salmon": "farm-raised salmon",
  "beluga lentils": "green or brown lentils",
  "microgreens": "baby spinach or arugula",
  "edible flowers": "fresh herbs (parsley, basil, thyme)",
  "mandarin zest": "orange zest",
  "truffle oil": "mushroom-flavored oil",
  "verjus": "white wine vinegar",
  "pink peppercorns": "black pepper",
  "fennel pollen": "ground fennel seeds",
  "kohlrabi": "cabbage or turnip",
  "sea beans": "green beans",
  "algae sheets (nori)": "spinach leaves",
  "black garlic": "regular roasted garlic",
  "kumquat puree": "orange juice",
  "bergamot": "lime or lemon zest",
  "pomegranate molasses": "balsamic reduction"
};
